#!/bin/bash
domain=$(sudo yunohost app setting rutorrent domain)
data_dir=$(sudo yunohost app setting rutorrent data_dir)

sudo service rtorrent stop

sudo rm -rf /var/www/rutorrent
sudo rm -rf $data_dir
sudo rm -f /etc/nginx/conf.d/$domain.d/rutorrent.conf
sudo rm -f /etc/init.d/rtorrent

# Remove the user
sudo userdel -f rtorrent
sudo rm -rf /home/rtorrent

# Remove the service
sudo yunohost service remove rtorrent

# Remove the sources
sudo rm -f /etc/apt/sources.list.d/rutorrent.list

#remove dependances
ynh_package_remove "libcppunit-dev libtool build-essential pkg-config libssl-dev libcurl4-openssl-dev libsigc++-2.0-dev libncurses5-dev screen subversion apache2-utils php5-cli php5-geoip unzip unrar rar zip ffmpeg buildtorrent mediainfo"

# Remove rtorrent
sudo rm -rf /usr/local/bin/rtorrent

sudo yunohost app ssowatconf
sudo service nginx reload
